<a href="https://colab.research.google.com/github/alijon070/ai_foundation/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd

In [6]:
mydataset = {
    'cars': ["BMW", "Volvo", "Ford", "Tesla", "Ferrari", "Ford", "BMW"],
    'counts': [3, 7, 2, 3, 4, 6, 6]
}

myvar = pd.DataFrame(mydataset)
print(myvar)

      cars  counts
0      BMW       3
1    Volvo       7
2     Ford       2
3    Tesla       3
4  Ferrari       4
5     Ford       6
6      BMW       6

In [8]:
myvar.head(1) # default first 5 rows

  cars  counts
0  BMW       3

In [9]:
myvar.tail() #  default last 5 rows

      cars  counts
2     Ford       2
3    Tesla       3
4  Ferrari       4
5     Ford       6
6      BMW       6

In [11]:
myvar.shape

(7, 2)

In [14]:
myvar.columns

Index(['cars', 'counts'], dtype='object')

In [16]:
myvar.dtypes

cars      object
counts     int64
dtype: object

In [17]:
myvar.describe() # numerical columns only

         counts
count  7.000000
mean   4.428571
std    1.902379
min    2.000000
25%    3.000000
50%    4.000000
75%    6.000000
max    7.000000

In [20]:
myvar.iloc[1:4]

    cars  counts
1  Volvo       7
2   Ford       2
3  Tesla       3

In [26]:
myvar.loc[2:5, "counts"]

2    2
3    3
4    4
5    6
Name: counts, dtype: int64

In [31]:
myvar[myvar["cars"]=="BMW"]

  cars  counts
0  BMW       3
6  BMW       6

In [34]:
# myvar.mean(numeric_only=True)
myvar["counts"].mean()

np.float64(4.428571428571429)

In [35]:
myvar.sum()

cars      BMWVolvoFordTeslaFerrariFordBMW
counts                                 31
dtype: object

In [36]:
myvar.min()

cars      BMW
counts      2
dtype: object

In [37]:
myvar.max()

cars      Volvo
counts        7
dtype: object

In [38]:
myvar.count()

cars      7
counts    7
dtype: int64

In [39]:
myvar.std(numeric_only=True)

counts    1.902379
dtype: float64

In [41]:
data_with_missing = {
    'cars': ["BMW", "Volvo", None, "Tesla", "Ferrari", None, "BMW"],
    'counts': [3, 7, None, 3, 4, None, 6]
}

df_missing = pd.DataFrame(data_with_missing)
print(df_missing)

      cars  counts
0      BMW     3.0
1    Volvo     7.0
2     None     NaN
3    Tesla     3.0
4  Ferrari     4.0
5     None     NaN
6      BMW     6.0

In [43]:
df_missing.isnull().sum()

cars      2
counts    2
dtype: int64

In [49]:
df_missing.dropna(subset=["cars"]) #axis=1, how="all"

      cars  counts
0      BMW     3.0
1    Volvo     7.0
3    Tesla     3.0
4  Ferrari     4.0
6      BMW     6.0

In [54]:
df_missing.fillna({"cars": "unknown", "counts": 0})

      cars counts
0      BMW    3.0
1    Volvo    7.0
2  unknown      0
3    Tesla    3.0
4  Ferrari    4.0
5  unknown      0
6      BMW    6.0

In [63]:
# df = pd.read_csv("Titanic-Dataset.csv")

df = pd.read_excel("output.xlsx")
# df = pd.read_json("Titanic-Dataset.json")
df.head(100)
df.tail()

,Unnamed: 0,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [60]:
df.to_excel("output.xlsx")

In [64]:
# Series => 1D
cars = pd.Series(["BMW", "Tesla", "Ferrari"] )
print(cars)

0        BMW
1      Tesla
2    Ferrari
dtype: object

In [65]:
car_series = data_with_missing["cars"]
print(car_series)

['BMW', 'Volvo', None, 'Tesla', 'Ferrari', None, 'BMW']